#!/usr/bin/with-contenv bash

# parse env vars to options
OPTIONS=""
if [[ ${NZBGET_USER} && ${NZBGET_USER-x} ]]; then
  OPTIONS+="-o ControlUsername=${NZBGET_USER} "
fi
if [[ ${NZBGET_PASS} && ${NZBGET_PASS-x} ]]; then
  OPTIONS+="-o ControlPassword=${NZBGET_PASS} "
fi
#git nzbToMedia Start
[ -d /app/nzbget/share/nzbget/scripts/nzbToMedia/.git ] || s6-setuidgid abc HOME=/home/abc git clone https://github.com/clinton-hall/nzbToMedia.git /app/nzbget/share/nzbget/scripts/nzbToMedia
#end
exec \
    s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf \
    -o OutputMode=log ${OPTIONS}
